services:
  mirakc:
    ports:
      - 40772:40772
    volumes:
      - miraview-html:/var/www/miraview:ro

  konomitv:
    devices:
      - '/dev/dri/:/dev/dri/'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu,video,utility]
    command:
      - /code/server/.venv/bin/python
      - KonomiTV.py
    volumes:
      - ./epgstation/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./epgstation/patch.sh:/usr/local/bin/patch.sh:ro
    entrypoint:
      - /usr/local/bin/docker-entrypoint.sh

  miraview:
    container_name: miraview
    image: docker.io/mirakc/mirakc:alpine
    restart: no
    volumes:
      - miraview-html:/var/www/miraview
    working_dir: /var/www/miraview
    environment:
      MIRAVIEW_VERSION: v0.1.2
    entrypoint: ash
    command: -c "curl -L https://github.com/maeda577/miraview/releases/download/$$MIRAVIEW_VERSION/build.tar.gz | tar -zxvf -"
      
volumes:
  miraview-html:
    name: miraview_html
    driver: local